name: Unit Test for Autogluon-Assistant UI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install uv
          uv pip install --system -e ".[dev]"
      - uses: streamlit/streamlit-app-action@v0.0.3
        with:
          app-path: src/autogluon/assistant/ui/app.py
          pytest-args: -v --junit-xml=test-results.xml
